### ISSUE TITLE
Failure installation

### ISSUE THREAD

**Issue by xkenpachi** [CloudBoost/swift-sdk#1]
I can not install from cocoapods. There is some mistakes.

**Comment by ricky051** [comment]
are you sure?

initialise pos in your project using 
```
pod init
```

Here is a sample pod file with CloudBoost included:

```
# Uncomment this line if you're using Swift
use_frameworks!

target 'ABC' do
pod "CloudBoost"
end

target 'ABCTests' do

end

target 'ABCUITests' do

end

```

install by:
```
pod install
```

and once you are done installing the pods,
link it in your ".xcworkspace" ( not .xcodeproject)
<img width="1512" alt="screen shot 2016-05-11 at 2 04 26 pm" src="https://cloud.githubusercontent.com/assets/10333542/15174904/78a1385a-1781-11e6-91b5-b5440ddd29a5.png">

**Comment by xkenpachi** [comment]
Yes I'm sure, and that is message : Emres-Mac-mini:Kombin emreoner$ pod install
Analyzing dependencies
[!] Unable to find a specification for `CloudBoost

**Comment by ricky051** [comment]
There might be an issue with you version of cocoa pods or Xcode. Are you able to install other pod repositories???

**Comment by xkenpachi** [comment]
Yes yes of course, i just install firebase before install CloudBoost.

**Comment by ricky051** [comment]
Okay,

I've made the following pod file with both Firebase and CloudBoost. This seems to be working for me. Could you please try and replace this with yours and install pods again?

[Podfile.zip](https://github.com/CloudBoost/swift-sdk/files/259729/Podfile.zip)

**Comment by xkenpachi** [comment]
Thats it!, thank you very much, now its okay but i don't understand where did i wrong? Regards.

**Comment by ricky051** [comment]
You might have missed something in the Podfile. Anyways, I'm glad it's working now 👍
