### ISSUE TITLE
General ACL issues

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/swift-sdk#10]
The following code 
```
object.getAcl()?.setPublicReadAccess(true)
object.getAcl()?.setPublicWriteAccess(true)

object.save { response in
}
```

generates on the backend an ACL with no read rights:
<img width="599" alt="schermata 2016-06-02 alle 13 36 51" src="https://cloud.githubusercontent.com/assets/867473/15743627/2863cd88-28c7-11e6-8c65-dce9672f7290.png">

It is also impossibile to grant rights for user with `setUserReadAccess` and `setUserWriteAccess`.

**Comment by ricky051** [comment]
Above code gets the ACL, but it wouldn't make any changes to the ACL of the itself 

```Swift
let acl = object.getAcl()!
acl.setPublicReadAccess(true)
acl.setPublicWriteAccess(true)
obj.setACL(acl)
```
