### ISSUE TITLE
Create custom objects from queries 

### ISSUE THREAD

**Issue by MicheleLonghi** [CloudBoost/swift-sdk#2]
That is: subclassing capabilities for CloudObject.

One possibile implementation is to specify a query optional property that defines the class to be constructed during fetch:
`query.objectClass = CustomClass.self`
where CusomClass is a subclass of CloudObject

Another possibile solution is to define in the CloudApp object a mapping dictionary:
`appCloud.tableMapping = [
"Invoice", Invoice.self,
"Customer", Customer.self
]
`

**Comment by MicheleLonghi** [comment]
I made a Pull request for this feature

https://github.com/CloudBoost/swift-sdk/pull/3/commits

**Comment by nawazdhandala** [comment]
Thank you for contributing. Let me review and get back.
