### ISSUE TITLE
Check if Latitude and Longitude are in range. (Refer JS SDK) 

### ISSUE THREAD

**Issue by nawazdhandala** [CloudBoost/swift-sdk#8]

**Comment by MicheleLonghi** [comment]
I can’t because the ACL doesn’t let me see that record in the client.

M

**Comment by nawazdhandala** [comment]
No, this is an SDK bug which needs to be fixed. 
P.S : User master key on the client to ignore all the ACL's

**Comment by MicheleLonghi** [comment]
The problem started with ACL management.
If you deny public access but grant access to the current user, the record is not fetched.

M

**Comment by MicheleLonghi** [comment]
ok, but on the dashboard has to be visible, in order to fix things.

M

**Comment by nawazdhandala** [comment]
Yes, I agree. We’re fixing the dashboard today. :) 

 

Regards,

Nawaz Dhandala.

**Comment by MicheleLonghi** [comment]
Thanks for support. I removed the damaged record and now table is visible on dashboard.

M

**Comment by ricky051** [comment]
the latitude and longitude checks are already being performed
